import { TutorialConfig } from "./types";

export const homePageTutorial: TutorialConfig = {
  pageKey: "home",
  completionKey: "tutorial:home:completed",
  steps: [
    {
      id: "welcome",
      targetSelector: '[data-tutorial="main-cta"]',
      title: "Сайн уу! Би таны туслах багш. Эхлэхийн тулд энд дарна уу!",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "streak",
      targetSelector: '[data-tutorial="streak-stat"]',
      title:
        "Энэ нь таны дэс дараалал. Өдөр бүр хичээл хийж дараалалаа хадгална!",
      character: "blue",
      characterPosition: "left",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "xp",
      targetSelector: '[data-tutorial="xp-stat"]',
      title:
        "Энэ нь таны цуглуулсан оноо. Хичээл дүүргэх тутам оноо нэмэгдэнэ!",
      character: "white",
      characterPosition: "left",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "dashboard",
      targetSelector: '[data-tutorial="dashboard-btn"]',
      title: "Та энд даран хүүхдүүдийхээ явцыг хянах боломжтой.",
      character: "blue",
      characterPosition: "right",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "users",
      targetSelector: '[data-tutorial="users-btn"]',
      title: "Энд дарснаар хүүхэд нэмэх боломжтой.",
      character: "yellow",
      characterPosition: "right",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "start",
      targetSelector: '[data-tutorial="main-cta"]',
      title: "Гайхалтай! Одоо та бэлэн боллоо. Сурах аялалаа эхлүүлцгээе!",
      character: "yellow",
      characterPosition: "right",
      tooltipPosition: "bottom",
      highlightTarget: false,
    },
  ],
};

export const lessonPageTutorial: TutorialConfig = {
  pageKey: "lesson",
  completionKey: "tutorial:lesson:completed",
  steps: [
    {
      id: "color-palette",
      targetSelector: '[data-tutorial="color-palette"]',
      title: "Энд дээр дарж өнгөө сонгоно уу!",
      character: "yellow",
      characterPosition: "right",
      tooltipPosition: "right",
      highlightTarget: true,
    },
    {
      id: "undo",
      targetSelector: '[data-tutorial="undo-btn"]',
      title: "Сүүлийн үйлдлийг буцаана.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "redo",
      targetSelector: '[data-tutorial="redo-btn"]',
      title: "Буцаасан үйлдлийг дахин хийнэ.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "help",
      targetSelector: '[data-tutorial="help-btn"]',
      title: "Тусламж хэрэгтэй бол энд дарна уу.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "download",
      targetSelector: '[data-tutorial="download-btn"]',
      title: "Зургаа татаж авна.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "done",
      targetSelector: '[data-tutorial="done-btn"]',
      title: "Дууссан бол энд дарж шалгуулна уу!",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
  ],
};
