import { TutorialConfig } from "./types";

export const homePageTutorial: TutorialConfig = {
  pageKey: "home",
  completionKey: "tutorial:home:completed",
  steps: [
    {
      id: "welcome",
      targetSelector: '[data-tutorial="main-cta"]',
      title: "Сайн уу! Би таны туслах багш. Эхлэхийн тулд энд дарна уу!",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "streak",
      targetSelector: '[data-tutorial="streak-stat"]',
      title:
        "Энэ нь таны дэс дараалал. Өдөр бүр хичээл хийж дараалалаа хадгална!",
      character: "blue",
      characterPosition: "left",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "xp",
      targetSelector: '[data-tutorial="xp-stat"]',
      title:
        "Энэ нь таны цуглуулсан оноо. Хичээл дүүргэх тутам оноо нэмэгдэнэ!",
      character: "white",
      characterPosition: "left",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
    {
      id: "fractions",
      targetSelector: '[data-tutorial="fractions-card"]',
      title: "Бутархай тоонуудтай танилцахыг хүсвэл энэ картыг сонгоорой.",
      character: "blue",
      characterPosition: "left",
      tooltipPosition: "top",
      highlightTarget: true,
    },
    {
      id: "multiplication",
      targetSelector: '[data-tutorial="multiplication-card"]',
      title: "Үржих үйлдлийг сурахдаа бэлэн үү? Энд дарна уу!",
      character: "white",
      characterPosition: "left",
      tooltipPosition: "top",
      highlightTarget: true,
    },
    {
      id: "complete",
      targetSelector: '[data-tutorial="main-cta"]',
      title: "Гайхалтай! Одоо та бэлэн боллоо. Сурах аялалаа эхлүүлцгээе!",
      character: "yellow",
      characterPosition: "right",
      tooltipPosition: "bottom",
      highlightTarget: true,
    },
  ],
};

export const lessonPageTutorial: TutorialConfig = {
  pageKey: "lesson",
  completionKey: "tutorial:lesson:completed",
  steps: [
    {
      id: "color-palette",
      targetSelector: '[data-tutorial="color-palette"]',
      title: "Энд дээр дарж өнгөө сонгоно уу!",
      character: "yellow",
      characterPosition: "right",
      tooltipPosition: "right",
      highlightTarget: true,
    },
    {
      id: "fullscreen",
      targetSelector: '[data-tutorial="fullscreen-btn"]',
      title: "Бүтэн дэлгэцээр харах.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "undo",
      targetSelector: '[data-tutorial="undo-btn"]',
      title: "Сүүлийн үйлдлийг буцаана.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "redo",
      targetSelector: '[data-tutorial="redo-btn"]',
      title: "Буцаасан үйлдлийг дахин хийнэ.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "reset",
      targetSelector: '[data-tutorial="reset-btn"]',
      title: "Бүгдийг устгаж эхнээс эхэлнэ.",
      character: "blue",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "download",
      targetSelector: '[data-tutorial="download-btn"]',
      title: "Зургаа татаж авна.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "eraser",
      targetSelector: '[data-tutorial="eraser-btn"]',
      title: "Буруу будсан бол энд дарж арилгана.",
      character: "blue",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "help",
      targetSelector: '[data-tutorial="help-btn"]',
      title: "Тусламж хэрэгтэй бол энд дарна уу.",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
    {
      id: "done",
      targetSelector: '[data-tutorial="done-btn"]',
      title: "Дууссан бол энд дарж шалгуулна уу!",
      character: "yellow",
      characterPosition: "left",
      tooltipPosition: "left",
      highlightTarget: true,
    },
  ],
};
